Fix out-of-tree builds when an in-tree build is present
Previously, if you ran

    $ ./configure
    $ make enc/ascii.o
    $ mkdir build
    $ cd build
    $ ../configure
    $ make enc/ascii.o

you would see

    compiling ../enc/ascii.c
    error: unable to open output file 'enc/ascii.o': 'No such file or directory'

because the `enc` dir did not exist.

The creation of that directory is gated by the `$(ENC_TRANS_D)`
directory, which expands to `.ext/.timestamp/.enc-trans.time`.

    $(BUILTIN_ENCOBJS) $(BUILTIN_TRANSOBJS): $(ENC_TRANS_D)

    $(ENC_TRANS_D):
    	$(Q) $(MAKEDIRS) enc/trans $(@D)

However, with an out-of-tree build, VPATH lookup would find
`..ext/.timestamp/.enc-trans.time`, assume it was up to date, and not
create the enc/trans directory in the current working dir.

Fix this by using an absolute path for .ext, to skip VPATH lookup.